# version keyword is omitted in order to use latest

services:

  redis:
    image: redis:7.2
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - tg_bot

  tgpt:
    build: .
    container_name: tgpt
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - bot_data:/data
    links:
      - redis
    networks:
      - tg_bot
      - proxy

volumes:
  redis_data:
  bot_data:

networks:
  tg_bot:
    driver: bridge
  proxy:
    driver: host