# version keyword is omitted in order to use latest

services:

  redis:
    image: redis:7.2
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - with_proxy

  tgpt:
    build: .
    container_name: tgpt
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - bot_data:/data
    links:
      - redis
    networks:
      - with_proxy

volumes:
  redis_data:
  bot_data:

networks:
  with_proxy:
    driver: host