# version keyword is omitted in order to use latest

services:

  redis:
    image: redis:7.2
    container_name: redis
    restart: always
    volumes:
      - redis_data:/data
    network_mode: host

  tgpt:
    build: .
    container_name: tgpt
    restart: always
    volumes:
      - bot_data:/data
    depends_on:
      - redis
    network_mode: host

volumes:
  redis_data:
  bot_data:
