# This is a basic workflow to upload files
# from GitHub to server via GitHub Actions
name: CI/CD

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]

jobs:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: updating
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd Desktop
            mkdir TeleGPT
            cd TeleGPT
            touch hello.txt