# Auto deploy on server
name: CI/CD

# when there are changes in github repo
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: updating/deploying
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |

            # working dir
            cd Desktop/tgpt

            # updating
            git pull origin main

            # activating python venv
            source venv/bin/activate

            # check if current repo old-pid exists and alive
            if ( [ -e "./nohup.pid" ] && [ $(ps -o pid= -p $(cat nohup.pid)) ] );
            then
              # kill pid and .pid file
              sudo kill `cat nohup.pid`
              rm nohup.pid
            fi

            # running processes in bg and saving its pid
            nohup python main.py 1>nohup.out 2>nohup.err & disown
            echo $! > nohup.pid