# Auto deploy on server
name: CI/CD

# when there are changes in github repo
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: updating/deploying
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          command_timeout: 200m
          script: |

            # working dir
            cd tgbot
            # pulling
            git pull origin main
            # removing old compose containers
            docker compose down
            # building new image
            docker compose build
            # building and running docker compose in bg
            docker compose up -d
            # live time stream logs (both std out and err) to file in detached mode:: https://stackoverflow.com/questions/41144589/how-to-redirect-docker-container-logs-to-a-single-file
            docker compose logs -f &> docker.log &

