# Auto deploy on server
name: CI/CD

# when there are changes in github repo
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: updating/deploying
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |

            # working dir
            cd Desktop/tgpt

            # updating
            # git pull origin main
            # fetching
            git fetch origin main
            # checking
            DIFF=$(git diff main..origin/main)
            if [[ $DIFF ]];
            then
              # updating
              git merge origin/main
              # building new image
              docker compose build
              # logging
              echo "repo is updated, new image is built"
            else
              # logging
              echo "no changes found"
            fi

            # run docker compose in bg
            # docker compose up -d

