# a basic workflow

name: CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: env_configuration
        id: env
        run: |
          ENV_EXISTS=`find . -name "pyvenv.cfg" | head -n 1`
          if [ -e "$ENV_EXISTS" ]
          then
            echo "env already exist"
            echo "new_venv=false" >> $GITHUB_ENV
          else
            echo "creating new venv"
            python -m venv
            cp ~/Secrets/TeleGPT .
            mv TeleGPT .env
            echo "new_venv=true" >> $GITHUB_ENV
          fi

      - name: activate_venv
        id: act
        run: source venv/bin/activate

      - name: old_env_configuration
        id: old_env_conf
        if: ${{ success() && github.new_venv=="false"}}
        run: |
          pip freeze > req.txt
          grep -xvFf requirements.txt req.txt > diff.txt
          if [ -s "diff.txt" ]
          then
            pip install -r requirements.txt
          fi
          rm -rf diff.txt
          rm -rf req.txt

      - name: deploy
        id: d
        run: python nohup main.py & disown

