# Auto deploy on server
name: CI/CD

# when there are changes in github repo
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: updating/deploying
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd Desktop/tgpt
            git pull origin main

            source venv/bin/activate
            [ -e "./nohup.pid" ] && { sudo kill `cat nohup.pid`; rm nohup.pid; }
            nohup python main.py > nohup.out & echo $! > nohup.pid